package main

import "time"

const (
	ERROR_CODE_GEO_RESTRICED     = 403
	ERROR_CODE_INTERNAL_SERVER   = 500
	ERROR_CODE_PARAMETERS        = 400
	ERROR_CODE_TOO_MANY_REQUESTS = 429
	ERROR_CODE_VIP_ONLY          = 403
	ERROR_CODE_VIP_STATUS        = 400

	ERROR_CODE_AUTH_ACCESS_KEY = 401
	ERROR_CODE_AUTH_BLACKLIST  = 403
	ERROR_CODE_AUTH_NOT_LOGIN  = 401
	ERROR_CODE_AUTH_WHITELIST  = 403

	ERROR_CODE_HEADER_MIN_VERSION = 400
	ERROR_CODE_HEADER_WRONG       = 400

	ERROR_CODE_MISSING_AREA     = 400
	ERROR_CODE_MISSING_TYPE     = 400
	ERROR_CODE_MISSING_KEYWORD  = 400
	ERROR_CODE_MISSING_COOKIE   = 400
	ERROR_CODE_MISSING_SS_OR_EP = 400
)

var LOCATION_SHANGHAI = time.FixedZone("Asia/Shanghai", 8)

const (
	TIME_FORMAT = "2006-01-02 15:04:05"

	MSG_ERROR_GEO_RESTRICTED    = "地区限制！"
	MSG_ERROR_INTERNAL_SERVER   = "解析服务器错误！"
	MSG_ERROR_PARAMETERS        = "参数错误！"
	MSG_ERROR_TOO_MANY_REQUESTS = "请求过于频繁！"
	MSG_ERROR_VIP_ONLY          = "仅限大会员用户！"
	MSG_ERROR_VIP_STATUS        = "大会员状态异常！"

	MSG_ERROR_AUTH_ACCESS_KEY = "access_key 错误或模块问题！"
	MSG_ERROR_AUTH_BLACKLIST  = "黑名单\nUID: %d\n解除时间: %s"
	MSG_ERROR_AUTH_NOT_LOGIN  = "账号未登录！"
	MSG_ERROR_AUTH_WHITELIST  = "本解析服务器仅限白名单用户使用！"

	MSG_ERROR_HEADER_MIN_VERSION = "模块版本过低！"
	MSG_ERROR_HEADER_WRONG       = "错误的请求头！"

	MSG_ERROR_MISSING_AREA     = "缺少 area 参数！"
	MSG_ERROR_MISSING_TYPE     = "缺少 type 参数！"
	MSG_ERROR_MISSING_KEYWORD  = "缺少 keyword 参数！"
	MSG_ERROR_MISSING_COOKIE   = "缺少 cookie！"
	MSG_ERROR_MISSING_SS_OR_EP = "缺少 season_id 或 ep_id 参数！"
)
