// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package entity

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson53c2c5caDecodeGithubComJasonKhew96BiliroamingGoServerEntity(in *jlexer.Lexer, out *HealthData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "last_check":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.LastCheck).UnmarshalJSON(data))
			}
		case "counter":
			out.Counter = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson53c2c5caEncodeGithubComJasonKhew96BiliroamingGoServerEntity(out *jwriter.Writer, in HealthData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"last_check\":"
		out.RawString(prefix[1:])
		out.Raw((in.LastCheck).MarshalJSON())
	}
	{
		const prefix string = ",\"counter\":"
		out.RawString(prefix)
		out.Int64(int64(in.Counter))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HealthData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson53c2c5caEncodeGithubComJasonKhew96BiliroamingGoServerEntity(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HealthData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson53c2c5caEncodeGithubComJasonKhew96BiliroamingGoServerEntity(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HealthData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson53c2c5caDecodeGithubComJasonKhew96BiliroamingGoServerEntity(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HealthData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson53c2c5caDecodeGithubComJasonKhew96BiliroamingGoServerEntity(l, v)
}
func easyjson53c2c5caDecodeGithubComJasonKhew96BiliroamingGoServerEntity1(in *jlexer.Lexer, out *Health) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "code":
			out.Code = int(in.Int())
		case "message":
			out.Message = string(in.String())
		case "data":
			(out.Data).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson53c2c5caEncodeGithubComJasonKhew96BiliroamingGoServerEntity1(out *jwriter.Writer, in Health) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Code))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		(in.Data).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Health) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson53c2c5caEncodeGithubComJasonKhew96BiliroamingGoServerEntity1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Health) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson53c2c5caEncodeGithubComJasonKhew96BiliroamingGoServerEntity1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Health) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson53c2c5caDecodeGithubComJasonKhew96BiliroamingGoServerEntity1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Health) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson53c2c5caDecodeGithubComJasonKhew96BiliroamingGoServerEntity1(l, v)
}
