// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AccessKeys             string
	PlayURLCaches          string
	THEpisodeCaches        string
	THSeason2Caches        string
	THSeason2EpisodeCaches string
	THSeasonCaches         string
	THSeasonEpisodeCaches  string
	THSubtitleCaches       string
	Users                  string
}{
	AccessKeys:             "access_keys",
	PlayURLCaches:          "play_url_caches",
	THEpisodeCaches:        "th_episode_caches",
	THSeason2Caches:        "th_season2_caches",
	THSeason2EpisodeCaches: "th_season2_episode_caches",
	THSeasonCaches:         "th_season_caches",
	THSeasonEpisodeCaches:  "th_season_episode_caches",
	THSubtitleCaches:       "th_subtitle_caches",
	Users:                  "users",
}
