// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("AccessKeys", testAccessKeysUpsert)

	t.Run("PlayURLCaches", testPlayURLCachesUpsert)

	t.Run("THEpisodeCaches", testTHEpisodeCachesUpsert)

	t.Run("THSeason2Caches", testTHSeason2CachesUpsert)

	t.Run("THSeason2EpisodeCaches", testTHSeason2EpisodeCachesUpsert)

	t.Run("THSeasonCaches", testTHSeasonCachesUpsert)

	t.Run("THSeasonEpisodeCaches", testTHSeasonEpisodeCachesUpsert)

	t.Run("THSubtitleCaches", testTHSubtitleCachesUpsert)

	t.Run("Users", testUsersUpsert)
}
