// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testTHSeasonCaches(t *testing.T) {
	t.Parallel()

	query := THSeasonCaches()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testTHSeasonCachesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &THSeasonCach{}
	if err = randomize.Struct(seed, o, thSeasonCachDBTypes, true, thSeasonCachColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := THSeasonCaches().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTHSeasonCachesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &THSeasonCach{}
	if err = randomize.Struct(seed, o, thSeasonCachDBTypes, true, thSeasonCachColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := THSeasonCaches().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := THSeasonCaches().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTHSeasonCachesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &THSeasonCach{}
	if err = randomize.Struct(seed, o, thSeasonCachDBTypes, true, thSeasonCachColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := THSeasonCachSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := THSeasonCaches().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTHSeasonCachesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &THSeasonCach{}
	if err = randomize.Struct(seed, o, thSeasonCachDBTypes, true, thSeasonCachColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := THSeasonCachExists(ctx, tx, o.SeasonID)
	if err != nil {
		t.Errorf("Unable to check if THSeasonCach exists: %s", err)
	}
	if !e {
		t.Errorf("Expected THSeasonCachExists to return true, but got false.")
	}
}

func testTHSeasonCachesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &THSeasonCach{}
	if err = randomize.Struct(seed, o, thSeasonCachDBTypes, true, thSeasonCachColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	thSeasonCachFound, err := FindTHSeasonCach(ctx, tx, o.SeasonID)
	if err != nil {
		t.Error(err)
	}

	if thSeasonCachFound == nil {
		t.Error("want a record, got nil")
	}
}

func testTHSeasonCachesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &THSeasonCach{}
	if err = randomize.Struct(seed, o, thSeasonCachDBTypes, true, thSeasonCachColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = THSeasonCaches().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testTHSeasonCachesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &THSeasonCach{}
	if err = randomize.Struct(seed, o, thSeasonCachDBTypes, true, thSeasonCachColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := THSeasonCaches().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testTHSeasonCachesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	thSeasonCachOne := &THSeasonCach{}
	thSeasonCachTwo := &THSeasonCach{}
	if err = randomize.Struct(seed, thSeasonCachOne, thSeasonCachDBTypes, false, thSeasonCachColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}
	if err = randomize.Struct(seed, thSeasonCachTwo, thSeasonCachDBTypes, false, thSeasonCachColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = thSeasonCachOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = thSeasonCachTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := THSeasonCaches().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testTHSeasonCachesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	thSeasonCachOne := &THSeasonCach{}
	thSeasonCachTwo := &THSeasonCach{}
	if err = randomize.Struct(seed, thSeasonCachOne, thSeasonCachDBTypes, false, thSeasonCachColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}
	if err = randomize.Struct(seed, thSeasonCachTwo, thSeasonCachDBTypes, false, thSeasonCachColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = thSeasonCachOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = thSeasonCachTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := THSeasonCaches().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func thSeasonCachBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *THSeasonCach) error {
	*o = THSeasonCach{}
	return nil
}

func thSeasonCachAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *THSeasonCach) error {
	*o = THSeasonCach{}
	return nil
}

func thSeasonCachAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *THSeasonCach) error {
	*o = THSeasonCach{}
	return nil
}

func thSeasonCachBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *THSeasonCach) error {
	*o = THSeasonCach{}
	return nil
}

func thSeasonCachAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *THSeasonCach) error {
	*o = THSeasonCach{}
	return nil
}

func thSeasonCachBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *THSeasonCach) error {
	*o = THSeasonCach{}
	return nil
}

func thSeasonCachAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *THSeasonCach) error {
	*o = THSeasonCach{}
	return nil
}

func thSeasonCachBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *THSeasonCach) error {
	*o = THSeasonCach{}
	return nil
}

func thSeasonCachAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *THSeasonCach) error {
	*o = THSeasonCach{}
	return nil
}

func testTHSeasonCachesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &THSeasonCach{}
	o := &THSeasonCach{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, thSeasonCachDBTypes, false); err != nil {
		t.Errorf("Unable to randomize THSeasonCach object: %s", err)
	}

	AddTHSeasonCachHook(boil.BeforeInsertHook, thSeasonCachBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	thSeasonCachBeforeInsertHooks = []THSeasonCachHook{}

	AddTHSeasonCachHook(boil.AfterInsertHook, thSeasonCachAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	thSeasonCachAfterInsertHooks = []THSeasonCachHook{}

	AddTHSeasonCachHook(boil.AfterSelectHook, thSeasonCachAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	thSeasonCachAfterSelectHooks = []THSeasonCachHook{}

	AddTHSeasonCachHook(boil.BeforeUpdateHook, thSeasonCachBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	thSeasonCachBeforeUpdateHooks = []THSeasonCachHook{}

	AddTHSeasonCachHook(boil.AfterUpdateHook, thSeasonCachAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	thSeasonCachAfterUpdateHooks = []THSeasonCachHook{}

	AddTHSeasonCachHook(boil.BeforeDeleteHook, thSeasonCachBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	thSeasonCachBeforeDeleteHooks = []THSeasonCachHook{}

	AddTHSeasonCachHook(boil.AfterDeleteHook, thSeasonCachAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	thSeasonCachAfterDeleteHooks = []THSeasonCachHook{}

	AddTHSeasonCachHook(boil.BeforeUpsertHook, thSeasonCachBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	thSeasonCachBeforeUpsertHooks = []THSeasonCachHook{}

	AddTHSeasonCachHook(boil.AfterUpsertHook, thSeasonCachAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	thSeasonCachAfterUpsertHooks = []THSeasonCachHook{}
}

func testTHSeasonCachesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &THSeasonCach{}
	if err = randomize.Struct(seed, o, thSeasonCachDBTypes, true, thSeasonCachColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := THSeasonCaches().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTHSeasonCachesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &THSeasonCach{}
	if err = randomize.Struct(seed, o, thSeasonCachDBTypes, true); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(thSeasonCachColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := THSeasonCaches().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTHSeasonCachToManySeasonTHSeasonEpisodeCaches(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a THSeasonCach
	var b, c THSeasonEpisodeCach

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, thSeasonCachDBTypes, true, thSeasonCachColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, thSeasonEpisodeCachDBTypes, false, thSeasonEpisodeCachColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, thSeasonEpisodeCachDBTypes, false, thSeasonEpisodeCachColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.SeasonID = a.SeasonID
	c.SeasonID = a.SeasonID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.SeasonTHSeasonEpisodeCaches().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.SeasonID == b.SeasonID {
			bFound = true
		}
		if v.SeasonID == c.SeasonID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := THSeasonCachSlice{&a}
	if err = a.L.LoadSeasonTHSeasonEpisodeCaches(ctx, tx, false, (*[]*THSeasonCach)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.SeasonTHSeasonEpisodeCaches); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.SeasonTHSeasonEpisodeCaches = nil
	if err = a.L.LoadSeasonTHSeasonEpisodeCaches(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.SeasonTHSeasonEpisodeCaches); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testTHSeasonCachToManyAddOpSeasonTHSeasonEpisodeCaches(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a THSeasonCach
	var b, c, d, e THSeasonEpisodeCach

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, thSeasonCachDBTypes, false, strmangle.SetComplement(thSeasonCachPrimaryKeyColumns, thSeasonCachColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*THSeasonEpisodeCach{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, thSeasonEpisodeCachDBTypes, false, strmangle.SetComplement(thSeasonEpisodeCachPrimaryKeyColumns, thSeasonEpisodeCachColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*THSeasonEpisodeCach{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddSeasonTHSeasonEpisodeCaches(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.SeasonID != first.SeasonID {
			t.Error("foreign key was wrong value", a.SeasonID, first.SeasonID)
		}
		if a.SeasonID != second.SeasonID {
			t.Error("foreign key was wrong value", a.SeasonID, second.SeasonID)
		}

		if first.R.Season != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Season != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.SeasonTHSeasonEpisodeCaches[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.SeasonTHSeasonEpisodeCaches[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.SeasonTHSeasonEpisodeCaches().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testTHSeasonCachesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &THSeasonCach{}
	if err = randomize.Struct(seed, o, thSeasonCachDBTypes, true, thSeasonCachColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTHSeasonCachesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &THSeasonCach{}
	if err = randomize.Struct(seed, o, thSeasonCachDBTypes, true, thSeasonCachColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := THSeasonCachSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTHSeasonCachesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &THSeasonCach{}
	if err = randomize.Struct(seed, o, thSeasonCachDBTypes, true, thSeasonCachColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := THSeasonCaches().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	thSeasonCachDBTypes = map[string]string{`SeasonID`: `bigint`, `IsVip`: `boolean`, `Data`: `json`, `CreatedAt`: `timestamp without time zone`, `UpdatedAt`: `timestamp without time zone`}
	_                   = bytes.MinRead
)

func testTHSeasonCachesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(thSeasonCachPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(thSeasonCachAllColumns) == len(thSeasonCachPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &THSeasonCach{}
	if err = randomize.Struct(seed, o, thSeasonCachDBTypes, true, thSeasonCachColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := THSeasonCaches().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, thSeasonCachDBTypes, true, thSeasonCachPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testTHSeasonCachesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(thSeasonCachAllColumns) == len(thSeasonCachPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &THSeasonCach{}
	if err = randomize.Struct(seed, o, thSeasonCachDBTypes, true, thSeasonCachColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := THSeasonCaches().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, thSeasonCachDBTypes, true, thSeasonCachPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(thSeasonCachAllColumns, thSeasonCachPrimaryKeyColumns) {
		fields = thSeasonCachAllColumns
	} else {
		fields = strmangle.SetComplement(
			thSeasonCachAllColumns,
			thSeasonCachPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := THSeasonCachSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testTHSeasonCachesUpsert(t *testing.T) {
	t.Parallel()

	if len(thSeasonCachAllColumns) == len(thSeasonCachPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := THSeasonCach{}
	if err = randomize.Struct(seed, &o, thSeasonCachDBTypes, true); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert THSeasonCach: %s", err)
	}

	count, err := THSeasonCaches().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, thSeasonCachDBTypes, false, thSeasonCachPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize THSeasonCach struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert THSeasonCach: %s", err)
	}

	count, err = THSeasonCaches().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
